<div class="row">
    <div class="col-4">
        <div class="profile-body">
            <div class="profile-container">
                <div class="profile-header">
                    <?php
                    echo "<img src= '../css" . $author->image_path . "' alt= 'profile not found' class='profile-pic'>";
                    echo "
                    <h1 class='profile-name'>" . $author->fullname . "</h1>
                    <p class='profile-bio'>" . $author->bio . "</p>";
                    
                    echo "
                        <a 
                            class='btn btn-light btn-sm rounded px-4 mt-2' 
                            href='?action=edit-profile'
                        >
                            Edit profile
                        </a>
                    ";
                    ?>
                </div>

                <div class="profile-interests">
                    <h2>Interests</h2>
                    <ul>
                        <?php
                        foreach ($author->interests as $interest) {
                            echo "<li>" . $interest . "</li>";
                        }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="col-8">
        <div class="container py-4 pe-5">
            <div class="row">
                <div class="col-6">
                  <h1>List of papers</h1>
                </div>
                <div class="col-6 text-end mt-2">
                  <a class="btn btn-secondary" href="?action=create-paper">
                    <i class="bi bi-plus"></i>
                    Add new paper 
                  </a>
                </div>
            </div>
            <?php
            foreach ($papers as $paper) {
                echo "<div class='card mt-4'>"; 
                echo "  <div class='card-body row'>";
                echo "
                    <div class='col-10'>
                        <h5 class='card-title pb-2'>
                            " . $paper->title . "
                        </h5>
                        <p class='card-text'><strong>Author: </strong>" . $paper->author_string_list . "</p>
                        <p class='card-text'><strong>Topic: </strong>" . $paper->topic_name . "</p>
                    </div>
                    <div class='col-2 text-end pt-4'> 
                        <a class='btn border-0' href='?action=paper-detail&paper_id=".$paper->paper_id."'>
                            <i class='bi bi-chevron-right'></i>
                        </a>
                    </div>
                    ";
                echo "  </div>";
                echo "</div>";
            }
            ?>
        </div>
    </div>
</div>
