<!DOCTYPE html>
<html>

<head>
    <title></title>
    <?php require("include/meta.phtml"); ?>
</head>

<body class="login-body">
    <div class="login-container">
        <h1 class="login-title">Login</h1>
        <form class="login-form"  method="post" action="?action=login&isLogin">
            <label class="login-label" for="username">Username</label>
            <input class="login-input" type="text" id="username" name="username" required>
            <label class="login-label" for="password">Password</label>
            <input class="login-input" type="password" id="password" name="password" required>
            <button class="login-button" type="submit">Login</button>
            
            <div class="p-2">
                <a href="index.php">To public page</a>
            </div>
        </form>
    </div>
</body>

</html>