<?php
foreach ($topics as $item) {
  echo "<div class='p-4'>";
  echo "  <div class='card'>";
  echo "    <div class='card-header'>Top 5: ".($item->topic_name)."</div>";
  echo "      <div class='card-body'>";

  foreach ($item->papers as $paper) {
    echo "
    <div class='row paper-card rounded p-2'>
      <div class='col-10'>
        <h5 class='text-bold'>Title: " . ($paper->title) . "</h5>
        <p>Authors - " . ($paper->author_string_list) . "</p>
      </div>
      <div class='col-2 text-end pt-3'> 
        <a class='btn border-0' href='?action=login'>
          <i class='bi bi-chevron-right'></i>
        </a>
      </div>
    </div>
    <hr/>
    ";
  }

  echo "    </div>";
  echo "    </div>";
  echo "  </div>";
  echo "</div>";
}
?>