<script type="text/javascript" language="javascript">
    var xmlHttp;
    function CreateXMLHttpRequest() {
        if (window.XMLHttpRequest) {
            // code for IE7+, Firefox, Chrome, Opera, Safari
            return new XMLHttpRequest()
        } else if (window.ActiveXObject) {
            // code for IE6, IE5
            return new ActiveXObject("Microsoft.XMLHTTP")
        }
    }

    function searchPapers(offset, rowsPerPage) {
        const searchValue = document.getElementById('search').value;
        const searchByValue = document.getElementById('searchBy').value;
        
        xmlHttp = CreateXMLHttpRequest();
        xmlHttp.onreadystatechange = showResult;
        setPaginationColor();

        xmlHttp.open('GET', `index.php?action=ajax-search&value=${searchValue}&searchBy=${searchByValue}&offset=${offset}&rowsPerPage=${rowsPerPage}`, true);
        xmlHttp.send(null);
    }

    function setPaginationColor() {
        const paginBtns = document.querySelectorAll('.pagination button');

        paginBtns.forEach(btn => {
            btn.addEventListener('click', function() {
                document.querySelector('.pagination button.active').classList.remove('active');
                this.classList.add('active');
            });
        })
    }

    function showResult()
	{
		if(xmlHttp.readyState == 4 && xmlHttp.status == 200)
		{
			var result = xmlHttp.responseText;
            document.getElementById("papersTable").innerHTML = result;
		}
	}
</script>

<div class="search-container">
    <div class="search-header">
        <h2>Search Papers</h2>
        <div class="search-filters">
            <div class="search-form-group">
                <label for="searchBy">Search by:</label>
                <select id="searchBy">
                    <option value="title">Title</option>
                    <option value="author_string_list">Authors</option>
                    <option value="name">Conferences</option>
                    <option value="topic_name">Topic</option>
                </select>
            </div>
        </div>
    </div>
    <form>
        <div class="search-form-group">
            <label for="search">Search:</label>
            <input type="text" id="search" placeholder="Enter search term" onkeyup="searchPapers(0,5)">
        </div>
        <button type="button" class="search-btn" onclick="searchPapers(0, 5)">Search</button>
    </form>

    <table id="papersTable" class="search-table">
        
    </table>

    <div class="pagination">
        <?php
            $page_size = 5;
            $max_page = ceil($papers_count / $page_size);

            echo "<button onclick='searchPapers(0, ".$page_size.")' class='active'>1</button>";

            for($i = 1; $i < $max_page; $i++) {
                $page_num = $i + 1;
                $offet = ($page_num - 1) * 3;
                
                echo "<button onclick='searchPapers(".$offet.", ".$page_size.")'>".$page_num."</button>";
            }
        ?>
    </div>
</div>